# Generated by Django 3.2.8 on 2021-11-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosswords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
